### ISSUE TITLE
Rename foreign keys?

### ISSUE THREAD

**Issue by gnewton** [DINA-Web/dina-workshop-2020#2]
Using 'foreign keys' (in reference to an identifier that is a key in another module) is both useful and misleading. Do we want to use another term/phrase, perhaps like "inter-module reference"? This would remove some of the fk baggage (think 'distributed transactions', 'cascading triggers on deletes', etc).

**Comment by cgendreau** [comment]
Indeed, I will rename it.

**Comment by cgendreau** [comment]
Updated in workshop document and https://github.com/DINA-Web/guidelines/issues/48
